name: RSpec
on: push

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.2

      - uses: actions/cache@v2
        with:
          path: .bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Set up dependences
        run: |
          gem install bundler
          bundle check || bundle install --jobs 4 --retry 3 --path .bundle

      - name: Run RSpec
        run: bundle exec rspec
        env:
          TZ: Asia/Tokyo
